### ISSUE TITLE
A long string of posts may not be displayed in full

### ISSUE THREAD

**Issue by creeping1023** [AkazaRenn/No-More-Sidebar-in-Mastodon-4.0#2]
查看长嘟文串的时候，最顶部或最底部会有部分空间不显示
Expand a string of posts which is longger than 100% width, and the top or botton part (depends on whether it is the first post of the string or not) may not be displayed (for overflow).

**Comment by AkazaRenn** [comment]
可以給我一個 post 的地址方便我測試嗎？

**Comment by CreepingG** [comment]
> 可以給我一個 post 的地址方便我測試嗎？

https://wxw.moe/@creeping_yoki/109501262419565382

**Comment by creeping1023** [comment]
> 可以給我一個 post 的地址方便我測試嗎？

https://wxw.moe/@creeping_yoki/109501262419565382

**Comment by AkazaRenn** [comment]
@creeping1023 我只能看到一條內容是「7」的嘟文耶。啊不過我在另一條嘟上測試了，現在應該也好了（好了
等 Salt 老師更新一下吧

**Comment by AkazaRenn** [comment]
Same root cause of https://github.com/AkazaRenn/No-More-Sidebar-in-Mastodon-4.0/issues/1
